/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Approvals */
        get: operations["list_approvals_api_admin_approvals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/approvals/{request_id}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Approval */
        post: operations["decide_approval_api_admin_approvals__request_id__decide_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Audit
         * @description `since`/`until` are ISO-8601 query params, which FastAPI parses into
         *     datetimes natively (and rejects with a 422 when unparseable, which is the
         *     right answer for a malformed bound). They bound `created_at` half-open,
         *     [since, until); a bound with no offset is read as UTC. See
         *     queries.list_audit and queries._as_utc for why on both counts.
         */
        get: operations["admin_audit_api_admin_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Conversations */
        get: operations["admin_conversations_api_admin_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Conversation Detail
         * @description Not audited, like every other admin read. The audit log records
         *     mutating calls (spec 14); a row per detail view would bury real events
         *     under navigation noise.
         */
        get: operations["admin_conversation_detail_api_admin_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Costs */
        get: operations["admin_costs_api_admin_costs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Lessons */
        get: operations["admin_lessons_api_admin_lessons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/lessons/{lesson_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Admin Archive Lesson
         * @description DELETE archives; it does not remove the row.
         *
         *     Spec 4.2 and parent spec 20 make lessons archivable so a bad lesson can be
         *     withdrawn from retrieval without destroying the record that it existed and
         *     was acted on. The row survives, the list keeps returning it, and the audit
         *     action says `lesson.archived` rather than `lesson.deleted` for the same
         *     reason.
         *
         *     Repeating the call on an already-archived lesson is idempotent -- 200 and
         *     the same body -- rather than a 409. The verb states a desired end state,
         *     that end state already holds, and a panel whose delete button errors on a
         *     double-click is worse than one that does nothing. The second audit row is
         *     NOT suppressed: it records that an admin issued the request, which is true
         *     whether or not the row changed, and dropping it because the write was a
         *     no-op is how an audit trail starts lying by omission.
         */
        delete: operations["admin_archive_lesson_api_admin_lessons__lesson_id__delete"];
        options?: never;
        head?: never;
        /**
         * Admin Patch Lesson
         * @description Same single-transaction contract as admin_patch_user: flush the change,
         *     stage the audit row, one commit.
         *
         *     Returns the full LessonSummary, not just {id, status}, so the panel can
         *     re-render the edited row from the response instead of re-fetching the
         *     list.
         */
        patch: operations["admin_patch_lesson_api_admin_lessons__lesson_id__patch"];
        trace?: never;
    };
    "/api/admin/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Overview */
        get: operations["admin_overview_api_admin_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Runs
         * @description `limit`/`offset` are typed as plain optional ints rather than
         *     constrained ones on purpose: the clamp lives in queries.clamp_limit so
         *     that an over-large limit is answered with the maximum page instead of a
         *     422. See that docstring for why.
         */
        get: operations["admin_runs_api_admin_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/runs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Runs Stream
         * @description Live run activity for the Traces screen.
         *
         *     Takes NO `db: DbSession`, deliberately. FastAPI exits the dependency
         *     stack only after the response completes, which for an SSE stream means
         *     when the client disconnects; Phase 6 measured that a stream holding its
         *     request session pins a pooled Postgres connection `idle in transaction`
         *     for the life of that stream, and about fifteen such streams exhaust the
         *     pool (pool_size=5 + max_overflow=10), after which login, chat and
         *     approvals all block. There is no backlog to replay here -- run history
         *     is available from GET /api/admin/runs -- so this endpoint needs no
         *     session at all, and an idle stream therefore holds nothing.
         *
         *     That also means there is no subscribe-before-read ordering hazard to
         *     manage, unlike the notification stream: with no snapshot read there is
         *     no window for an event to fall between the two sources.
         *
         *     `async def`, unlike every other route in this module: the whole body is
         *     awaiting a queue, so there is nothing to push into a threadpool, and a
         *     sync generator could not await the broker at all.
         */
        get: operations["admin_runs_stream_api_admin_runs_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/runs/{run_id}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Run Trace
         * @description Takes NO `db: DbSession`: trace_tree opens its own session by design
         *     (app/tracing/store.py), because a trace must be readable independently
         *     of any business transaction, so the dependency here was declared and
         *     never used. Measured, so as not to overstate it: an unused Session
         *     checks nothing out of the pool -- SQLAlchemy acquires a connection
         *     lazily, on the first statement -- so this cost nothing today. It is
         *     removed because it was one `db.query(...)` away from costing a pooled
         *     connection per request for a read that already has its own.
         *
         *     trace_tree raises ValueError for an unknown run id; that is the only
         *     ValueError it can raise, so translating it to 404 cannot mask an
         *     unrelated failure.
         */
        get: operations["admin_run_trace_api_admin_runs__run_id__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/tickets/{ticket_id}/dossier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin Ticket Dossier
         * @description Sync `def`, like the approvals routes and for the same reason: this
         *     performs a multi-second blocking model call, and Starlette runs a sync
         *     endpoint in a threadpool so that block cannot stall the event loop and
         *     therefore cannot stall every open SSE stream.
         *
         *     The client is fetched only AFTER the ticket is found, so a 404 neither
         *     requires an API key to be configured nor risks paying for a call with
         *     nothing to summarise.
         */
        post: operations["admin_ticket_dossier_api_admin_tickets__ticket_id__dossier_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Admin Users
         * @description The payload is an explicit dict rather than a dump of the row, so a
         *     column cannot join the API by being added to the table -- `password_hash`
         *     sits on the same object.
         */
        get: operations["admin_users_api_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Admin Patch User
         * @description Changes role and/or clearance and audits the change.
         *
         *     The mutation and its `audit_log` row share ONE transaction: the change is
         *     flushed, `record_audit` stages and flushes its row (it never commits --
         *     see app/audit/service.py), and a single `db.commit()` at the end makes
         *     both durable together. An audit entry that survived a rolled-back
         *     mutation would be a forensic lie, and one lost while the mutation stuck
         *     would be a silent gap; neither is possible while there is exactly one
         *     commit. tests/test_admin_mutations.py injects a failure after the audit
         *     row is staged and proves nothing survives.
         *
         *     The previous values go into the payload as well as the new ones: an audit
         *     row saying only what a field became cannot answer "what changed", which
         *     is the question the table exists for.
         */
        patch: operations["admin_patch_user_api_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/attachments/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Attachment */
        get: operations["get_attachment_api_attachments__attachment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/guest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Guest Login */
        post: operations["guest_login_api_auth_guest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations Endpoint */
        get: operations["list_conversations_endpoint_api_conversations_get"];
        put?: never;
        /** Create Conversation Endpoint */
        post: operations["create_conversation_endpoint_api_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation Endpoint */
        get: operations["get_conversation_endpoint_api_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Attachment */
        post: operations["upload_attachment_api_conversations__conversation_id__attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message Endpoint */
        post: operations["send_message_endpoint_api_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_api_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Notifications
         * @description Takes NO `db: DbSession` dependency, on purpose.
         *
         *     FastAPI tears the dependency stack down only after the response is
         *     complete, and an SSE response completes when the client disconnects. A
         *     dependency-provided session would therefore stay checked out of the
         *     pool -- and, once it had read anything, `idle in transaction` -- for the
         *     entire life of the stream. Measured: three open streams held three such
         *     backends. The pool is pool_size=5 + max_overflow=10, so about fifteen
         *     concurrent streams exhaust it and every other request (login, chat,
         *     approvals) blocks and then fails; long-lived open snapshots also hold
         *     back xmin and stop VACUUM from reclaiming anything. The backlog read
         *     below gets its own session, closed before the keepalive loop begins,
         *     so an idle stream holds no connection at all.
         */
        get: operations["stream_notifications_api_notifications_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Notification Read */
        post: operations["mark_notification_read_api_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tickets */
        get: operations["list_tickets_api_tickets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ticket */
        get: operations["get_ticket_api_tickets__ticket_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Ticket */
        patch: operations["update_ticket_api_tickets__ticket_id__patch"];
        trace?: never;
    };
    "/api/tickets/{ticket_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Ticket Endpoint */
        post: operations["resolve_ticket_endpoint_api_tickets__ticket_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalResponse */
        ApprovalResponse: {
            /** Action Payload */
            action_payload: {
                [key: string]: unknown;
            };
            /** Action Type */
            action_type: string;
            /** Agent Summary */
            agent_summary: string;
            /** Conversation Id */
            conversation_id: string;
            /** Decision Note */
            decision_note: string | null;
            /** Execution Result */
            execution_result: {
                [key: string]: unknown;
            } | null;
            /** Id */
            id: string;
            /** Justification */
            justification: string;
            /** Request Number */
            request_number: string;
            /** Risk Level */
            risk_level: string;
            /** Status */
            status: string;
        };
        /** AssigneeRecommendation */
        AssigneeRecommendation: {
            /** Helpdesk Ref */
            helpdesk_ref: string;
            /** Rationale */
            rationale: string;
            /** Specialization */
            specialization: string;
        };
        /** AttachmentResponse */
        AttachmentResponse: {
            /** Filename */
            filename: string;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Mime Type */
            mime_type: string;
            /** Parse Error */
            parse_error: string | null;
            /** Parse Status */
            parse_status: string;
            /** Size Bytes */
            size_bytes: number;
        };
        /**
         * AuditEntry
         * @description `target_type`, `target_id` and `payload` are NOT NULL in the table, so
         *     they are not optional here. A published schema looser than the data makes
         *     every consumer write a null check for a case that cannot occur.
         *     `actor_id` and `ip_address` genuinely are nullable.
         */
        AuditEntry: {
            /** Action */
            action: string;
            /** Actor Id */
            actor_id: string | null;
            /** Actor Type */
            actor_type: string;
            /** Created At */
            created_at: string | null;
            /** Id */
            id: string;
            /** Ip Address */
            ip_address: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Target Id */
            target_id: string;
            /** Target Type */
            target_type: string;
        };
        /** Body_upload_attachment_api_conversations__conversation_id__attachments_post */
        Body_upload_attachment_api_conversations__conversation_id__attachments_post: {
            /** File */
            file: string;
        };
        /**
         * Clearance
         * @enum {string}
         */
        Clearance: "standard" | "sensitive" | "privileged";
        /**
         * ConversationDetail
         * @description GET /conversations/{id}. Parent spec 15 wants the transcript beside
         *     its span tree, so this returns both halves in one call: the messages,
         *     and enough of each run to render a row that links into the trace view.
         */
        ConversationDetail: {
            conversation: components["schemas"]["ConversationSummary"];
            /** Messages */
            messages: components["schemas"]["MessageView"][];
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
        };
        /** ConversationResponse */
        ConversationResponse: {
            /** Id */
            id: string;
            /**
             * Messages
             * @default []
             */
            messages: components["schemas"]["MessageView"][];
            /** Status */
            status: string;
            /** Title */
            title: string | null;
        };
        /** ConversationSummary */
        ConversationSummary: {
            /** Created At */
            created_at: string | null;
            /** Full Name */
            full_name: string | null;
            /** Guest Email */
            guest_email: string | null;
            /** Guest Name */
            guest_name: string | null;
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Title */
            title: string | null;
            /** User Id */
            user_id: string | null;
            /** Username */
            username: string | null;
        };
        /** CostByDay */
        CostByDay: {
            /** Cost Usd */
            cost_usd: number;
            /** Day */
            day: string;
        };
        /** CostByModel */
        CostByModel: {
            /** Calls */
            calls: number;
            /** Cost Usd */
            cost_usd: number;
            /** Model */
            model: string;
            /** Unpriced Calls */
            unpriced_calls: number;
        };
        /** CostByTrigger */
        CostByTrigger: {
            /** Cost Usd */
            cost_usd: number;
            /** Runs */
            runs: number;
            /** Trigger */
            trigger: string;
        };
        /** CostByUser */
        CostByUser: {
            /** Cost Usd */
            cost_usd: number;
            /** Username */
            username: string;
        };
        /** CostSummary */
        CostSummary: {
            /** Cost Usd */
            cost_usd: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
        };
        /** CostTotals */
        CostTotals: {
            /** Cache Hit Rate */
            cache_hit_rate: number;
            /** Cache Read Tokens */
            cache_read_tokens: number;
            /** Cache Write Tokens */
            cache_write_tokens: number;
            /** Cost Usd */
            cost_usd: number;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Unpriced Calls */
            unpriced_calls: number;
        };
        /** Costs */
        Costs: {
            /** By Day */
            by_day: components["schemas"]["CostByDay"][];
            /** By Model */
            by_model: components["schemas"]["CostByModel"][];
            /** By Trigger */
            by_trigger: components["schemas"]["CostByTrigger"][];
            /** By User */
            by_user: components["schemas"]["CostByUser"][];
            totals: components["schemas"]["CostTotals"];
        };
        /** CreateConversationRequest */
        CreateConversationRequest: {
            /** Title */
            title?: string | null;
        };
        /** DecideRequest */
        DecideRequest: {
            /** Approve */
            approve: boolean;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** GuestRequest */
        GuestRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncidentDossier */
        IncidentDossier: {
            /** Agent Reasoning Summary */
            agent_reasoning_summary: string;
            /** Classification */
            classification: string;
            cost_summary: components["schemas"]["CostSummary"];
            /** Evidence */
            evidence: string[];
            /** Knowledge Sources */
            knowledge_sources: components["schemas"]["SourceCitation"][];
            /** Open Questions */
            open_questions: string[];
            /** Problem Statement */
            problem_statement: string;
            recommended_assignee: components["schemas"]["AssigneeRecommendation"];
            /** Recommended Next Actions */
            recommended_next_actions: string[];
            requester: components["schemas"]["RequesterInfo"];
            /** Risk Flags */
            risk_flags: components["schemas"]["RiskFlag"][];
            /** Severity */
            severity: string;
            /** Ticket Number */
            ticket_number: string;
            /** Timeline */
            timeline: components["schemas"]["TimelineEntry"][];
            /** Tools Invoked */
            tools_invoked: components["schemas"]["ToolInvocation"][];
        };
        /**
         * LessonDeleteResult
         * @description `archived` is redundant with `status == "archived"` but the router
         *     body already carries it (tests/test_admin_mutations.py asserts it
         *     verbatim), and a response_model must widen to fit an existing body
         *     rather than silently drop a field from it.
         */
        LessonDeleteResult: {
            /** Archived */
            archived: boolean;
            /** Id */
            id: string;
            /** Status */
            status: string;
        };
        /**
         * LessonPatch
         * @description Content, title and status. Not `category`, `file_path`, `ticket_id` or
         *     `created_by_run_id`: those are the lesson's provenance, the chain that
         *     makes it auditable at all, and an admin correcting the text of a lesson
         *     must not be able to re-attribute it to a different ticket or run.
         */
        LessonPatch: {
            /** Content Md */
            content_md?: string | null;
            status?: components["schemas"]["LessonStatus"] | null;
            /** Title */
            title?: string | null;
        };
        /**
         * LessonStatus
         * @enum {string}
         */
        LessonStatus: "active" | "archived";
        /** LessonSummary */
        LessonSummary: {
            /** Category */
            category: string;
            /** Confidence */
            confidence: string;
            /** Content Md */
            content_md: string;
            /** Created At */
            created_at: string | null;
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** Ticket Id */
            ticket_id: string | null;
            /** Title */
            title: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * MessageView
         * @description `content` is the stored content-block list exactly as the model
         *     exchanged it -- text blocks, image blocks, tool results. It is `Any`
         *     because that union is defined by the Anthropic API, not by us, and
         *     narrowing it here would silently drop block kinds we do not yet know.
         */
        MessageView: {
            /** Content */
            content: unknown;
            /** Created At */
            created_at: string | null;
            /** Id */
            id: string;
            /** Role */
            role: string;
            /** Run Id */
            run_id: string | null;
        };
        /** NotificationResponse */
        NotificationResponse: {
            /** Body */
            body: string;
            /** Created At */
            created_at: string | null;
            /** Id */
            id: string;
            /** Link Id */
            link_id: string | null;
            /** Link Type */
            link_type: string | null;
            /** Read */
            read: boolean;
            /** Title */
            title: string;
            /** Type */
            type: string;
        };
        /**
         * Overview
         * @description GET /overview. `error_rate` is a fraction of today's COMPLETED runs,
         *     not of every run -- in-flight ones have no outcome yet to be wrong.
         */
        Overview: {
            /** Error Rate */
            error_rate: number;
            /** Open Tickets */
            open_tickets: number;
            /** Pending Approvals */
            pending_approvals: number;
            /** Runs Today */
            runs_today: number;
            /** Spend Today */
            spend_today: number;
        };
        /** PageResponse[AuditEntry] */
        PageResponse_AuditEntry_: {
            /** Items */
            items: components["schemas"]["AuditEntry"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** PageResponse[ConversationSummary] */
        PageResponse_ConversationSummary_: {
            /** Items */
            items: components["schemas"]["ConversationSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** PageResponse[LessonSummary] */
        PageResponse_LessonSummary_: {
            /** Items */
            items: components["schemas"]["LessonSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** PageResponse[RunSummary] */
        PageResponse_RunSummary_: {
            /** Items */
            items: components["schemas"]["RunSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** PageResponse[UserSummary] */
        PageResponse_UserSummary_: {
            /** Items */
            items: components["schemas"]["UserSummary"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** PrincipalResponse */
        PrincipalResponse: {
            /** Clearance */
            clearance: string | null;
            /** Department */
            department: string | null;
            /** Employee Ref */
            employee_ref: string | null;
            /** Full Name */
            full_name: string | null;
            /** Helpdesk Ref */
            helpdesk_ref: string | null;
            /** Kind */
            kind: string;
            /** Role */
            role: string;
            /** User Id */
            user_id: string | null;
            /** Username */
            username: string | null;
        };
        /** RequesterInfo */
        RequesterInfo: {
            /** Clearance */
            clearance?: string | null;
            /** Department */
            department?: string | null;
            /** Name */
            name: string;
            /** Role */
            role: string;
        };
        /** ResolveTicketRequest */
        ResolveTicketRequest: {
            /** Resolution */
            resolution: string;
        };
        /** RiskFlag */
        RiskFlag: {
            /** Detail */
            detail: string;
            /** Kind */
            kind: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "guest" | "employee" | "helpdesk" | "admin";
        /**
         * RunSummary
         * @description GET /runs. Deliberately narrower than TraceRun below: the list needs
         *     enough to render a row, not the token breakdown.
         */
        RunSummary: {
            /** Cost Usd */
            cost_usd: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Error */
            error: string | null;
            /** Id */
            id: string;
            /** Llm Calls */
            llm_calls: number | null;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Tool Calls */
            tool_calls: number | null;
            /** Trigger */
            trigger: string;
        };
        /**
         * RunTrace
         * @description `truncated` is why this is not just {run, roots}.
         *
         *     A trace is unbounded in the data: one run's tree measured 167,617 bytes
         *     here, and nothing stops a longer agentic run being far larger. Spans
         *     beyond `span_cap` are dropped and the flag says so, because a silently
         *     shortened waterfall is worse than a short one -- an admin reading it
         *     would conclude the run simply stopped there.
         */
        RunTrace: {
            /** Roots */
            roots: components["schemas"]["SpanNode"][];
            run: components["schemas"]["TraceRun"];
            /** Span Count */
            span_count: number;
            /** Truncated */
            truncated: boolean;
        };
        /** SendMessageRequest */
        SendMessageRequest: {
            /** Content */
            content: string;
        };
        /** SourceCitation */
        SourceCitation: {
            /** Document Id */
            document_id: string;
            /** Why It Mattered */
            why_it_mattered: string;
        };
        /**
         * SpanNode
         * @description One node of the waterfall. `input`/`output` are already redacted at
         *     persistence time by tracing/redaction.py; this does not re-redact and
         *     must not be relied on to.
         */
        SpanNode: {
            /** Cache Read Tokens */
            cache_read_tokens: number | null;
            /** Cache Write Tokens */
            cache_write_tokens: number | null;
            /** Children */
            children: components["schemas"]["SpanNode"][];
            /** Cost Usd */
            cost_usd: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Error */
            error: string | null;
            /** Id */
            id: string;
            /** Input */
            input: unknown | null;
            /** Input Tokens */
            input_tokens: number | null;
            /** Kind */
            kind: string;
            /** Model */
            model: string | null;
            /** Name */
            name: string;
            /** Output */
            output: unknown | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Status */
            status: string;
        };
        /** TicketDetail */
        TicketDetail: {
            /** Assignee Helpdesk Ref */
            assignee_helpdesk_ref: string;
            /** Assignment Rationale */
            assignment_rationale: string;
            /** Assignment Score */
            assignment_score: number;
            /** Body */
            body: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Matched Specialization */
            matched_specialization: string;
            /** Priority */
            priority: string;
            /** Resolution */
            resolution: string | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Status */
            status: string;
            /** Ticket Number */
            ticket_number: string;
            /** Title */
            title: string;
        };
        /**
         * TicketPriority
         * @enum {string}
         */
        TicketPriority: "low" | "medium" | "high" | "urgent";
        /**
         * TicketStatus
         * @enum {string}
         */
        TicketStatus: "open" | "assigned" | "in_progress" | "resolved" | "closed" | "escalated";
        /** TicketSummary */
        TicketSummary: {
            /** Assignee Helpdesk Ref */
            assignee_helpdesk_ref: string;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Priority */
            priority: string;
            /** Status */
            status: string;
            /** Ticket Number */
            ticket_number: string;
            /** Title */
            title: string;
        };
        /** TimelineEntry */
        TimelineEntry: {
            /** At */
            at: string;
            /** What */
            what: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ToolInvocation */
        ToolInvocation: {
            /** Name */
            name: string;
            /** Summary */
            summary: string;
        };
        /**
         * TraceRun
         * @description The run header on GET /runs/{id}/trace -- the full token breakdown,
         *     unlike RunSummary.
         */
        TraceRun: {
            /** Cache Read Tokens */
            cache_read_tokens: number | null;
            /** Cache Write Tokens */
            cache_write_tokens: number | null;
            /** Cost Usd */
            cost_usd: number | null;
            /** Duration Ms */
            duration_ms: number | null;
            /** Error */
            error: string | null;
            /** Id */
            id: string;
            /** Input Tokens */
            input_tokens: number | null;
            /** Output Tokens */
            output_tokens: number | null;
            /** Started At */
            started_at: string | null;
            /** Status */
            status: string;
            /** Trigger */
            trigger: string;
        };
        /** UpdateTicketRequest */
        UpdateTicketRequest: {
            /** Assignee Helpdesk Ref */
            assignee_helpdesk_ref?: string | null;
            priority?: components["schemas"]["TicketPriority"] | null;
            /** Reassignment Rationale */
            reassignment_rationale?: string | null;
            status?: components["schemas"]["TicketStatus"] | null;
        };
        /**
         * UserPatch
         * @description Role and clearance, and nothing else.
         *
         *     `extra: "ignore"` is Pydantic's default, but it is stated explicitly
         *     because it is load-bearing here rather than incidental: it is what turns
         *     an attempt to smuggle `password_hash`, `username` or `id` through this
         *     route into a no-op instead of a privilege escalation that no audit row
         *     would explain. tests/test_admin_mutations.py exercises it directly, so
         *     the behaviour cannot be changed silently.
         *
         *     Both fields are optional and an omitted one means "leave it alone", not
         *     "set it to null" -- a PATCH that cleared clearance on every role change
         *     would quietly demote privileged accounts. The enum types do the
         *     validation: an unknown role is a 422 before the handler runs, so the row
         *     is never touched.
         */
        UserPatch: {
            clearance?: components["schemas"]["Clearance"] | null;
            role?: components["schemas"]["Role"] | null;
        };
        /** UserPatchResult */
        UserPatchResult: {
            /** Clearance */
            clearance: string | null;
            /** Id */
            id: string;
            /** Role */
            role: string;
        };
        /** UserSummary */
        UserSummary: {
            /** Clearance */
            clearance: string | null;
            /** Department */
            department: string | null;
            /** Dev Seed */
            dev_seed: boolean;
            /** Email */
            email: string;
            /** Employee Ref */
            employee_ref: string | null;
            /** Full Name */
            full_name: string;
            /** Helpdesk Ref */
            helpdesk_ref: string | null;
            /** Id */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Role */
            role: string;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_approvals_api_admin_approvals_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_approval_api_admin_approvals__request_id__decide_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_audit_api_admin_audit_get: {
        parameters: {
            query?: {
                actor_id?: string | null;
                action?: string | null;
                target_type?: string | null;
                since?: string | null;
                until?: string | null;
                limit?: number | null;
                offset?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_AuditEntry_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_conversations_api_admin_conversations_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number | null;
                offset?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_ConversationSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_conversation_detail_api_admin_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_costs_api_admin_costs_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Costs"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_lessons_api_admin_lessons_get: {
        parameters: {
            query?: {
                limit?: number | null;
                offset?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_LessonSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_archive_lesson_api_admin_lessons__lesson_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                lesson_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_patch_lesson_api_admin_lessons__lesson_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                lesson_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LessonPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_overview_api_admin_overview_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_runs_api_admin_runs_get: {
        parameters: {
            query?: {
                limit?: number | null;
                offset?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_RunSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_runs_stream_api_admin_runs_stream_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_run_trace_api_admin_runs__run_id__trace_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunTrace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_ticket_dossier_api_admin_tickets__ticket_id__dossier_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDossier"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_users_api_admin_users_get: {
        parameters: {
            query?: {
                limit?: number | null;
                offset?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse_UserSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_patch_user_api_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPatchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_attachment_api_attachments__attachment_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                attachment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    guest_login_api_auth_guest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrincipalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresh_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_endpoint_api_conversations_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_endpoint_api_conversations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_endpoint_api_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_attachment_api_conversations__conversation_id__attachments_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_attachment_api_conversations__conversation_id__attachments_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttachmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_endpoint_api_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_notifications_api_notifications_get: {
        parameters: {
            query?: {
                unread_only?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_notifications_api_notifications_stream_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_notification_read_api_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                notification_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tickets_api_tickets_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TicketStatus"] | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ticket_api_tickets__ticket_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ticket_api_tickets__ticket_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTicketRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_ticket_endpoint_api_tickets__ticket_id__resolve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveTicketRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
